version: '3.8'

services:
  crawler-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - CHROME_BIN=/usr/bin/google-chrome
    volumes:
      - ./examples:/app/examples:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
